# Generated by Django 4.2.6 on 2024-01-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=30)),
                ('memberemail', models.EmailField(max_length=254)),
                ('memberphone', models.CharField(max_length=12)),
                ('memberaddress', models.CharField(max_length=50)),
                ('donated_items', models.CharField(max_length=100)),
                ('donation_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
